CREATE TABLE USERS (
  ID         VARCHAR(8000) NOT NULL,
  first_name VARCHAR(1000),
  last_name  VARCHAR(1000),
  PRIMARY KEY (id)
);

CREATE TABLE LOCATIONS (
  ID    VARCHAR(8000) NOT NULL,
  CITY  VARCHAR(1000),
  STATE VARCHAR(1000),
  PRIMARY KEY (id)
);

CREATE TABLE USER_HAS_LOCATIONS (
  ID          VARCHAR(8000) NOT NULL,
  USER_ID     VARCHAR(8000) NOT NULL,
  LOCATION_ID VARCHAR(8000) NOT NULL,
  FOREIGN KEY (USER_ID) REFERENCES USERS (ID),
  FOREIGN KEY (LOCATION_ID) REFERENCES LOCATIONS (ID),
  PRIMARY KEY (ID)
);
